apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi
  namespace: fastapi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fastapi
  template:
    metadata:
      labels:
        app: fastapi
    spec:
      containers:
      - name: fastapi
        image: your-docker-image-for-fastapi:latest
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_HOST
          value: "redis"
        - name: RABBITMQ_HOST
          value: "rabbitmq"
---
apiVersion: v1
kind: Service
metadata:
  name: fastapi
  namespace: fastapi-dev
spec:
  selector:
    app: fastapi
  ports:
    - protocol: TCP
      port: 8000
