apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  namespace: fastapi-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      containers:
      - name: rabbitmq
        image: bitnami/rabbitmq:3.7
        ports:
        - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  namespace: fastapi-dev
spec:
  selector:
    app: rabbitmq
  ports:
    - protocol: TCP
      port: 5672
